#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"

export MINERVA_JUDGE_CLASSIFIER_MODEL="answerdotai/ModernBERT-base"
export MINERVA_JUDGE_CLASSIFIER_MAX_LEN="2048"
export MINERVA_JUDGE_CLASSIFIER_OUTPUT="${MINERVA_JUDGE_CLASSIFIER_OUTPUT:-$ROOT_DIR/classifier/outputs/modernbert-base-2k}"
export MINERVA_JUDGE_CLASSIFIER_BATCH_SIZE="${MINERVA_JUDGE_CLASSIFIER_BATCH_SIZE:-128}"
export MINERVA_JUDGE_CLASSIFIER_GRAD_ACCUM="${MINERVA_JUDGE_CLASSIFIER_GRAD_ACCUM:-1}"
export MINERVA_JUDGE_CLASSIFIER_BF16="${MINERVA_JUDGE_CLASSIFIER_BF16:-1}"

bash "$ROOT_DIR/run_train_longformer.sh"
