COMMON:
  log_dir: dataset/logs
  nvd_start_date: 2023-01-01
  nvd_end_date: 2024-12-31
  nvd_data_dir: dataset/nvd
  metadata_path: dataset/minerva/metadata.json

NVD:
  delay_s: 6.0

MITRE_ATTACK:
  attack_url: "https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json"
  cache_path: dataset/mitre/enterprise-attack.json

CAPEC:
  capec_url: "https://raw.githubusercontent.com/mitre/cti/master/capec/2.1/stix-capec.json"
  cache_path: dataset/capec/stix-capec.json

MAPPINGS_EXPLORER:
  ask_subtechnique: true

SIGMA:
  ask_subtechnique: true

TASKS:
  CVE_CWE:
    min_words: 30
    output_path: dataset/minerva/cve_to_cwe.jsonl
    seed: 1337
    max_items: 999999999
  CVE_CVSS_V31:
    min_words: 30
    prefer_nvd: true
    output_path: dataset/minerva/cve_to_cvss_v31.jsonl
    seed: 1337
    max_items: 999999999
  CVE_CVSS_V40:
    min_words: 30
    prefer_nvd: true
    output_path: dataset/minerva/cve_to_cvss_v40.jsonl
    seed: 1337
    max_items: 999999999
  SCENARIO_TECHNIQUE:
    max_items: 999999999
    ask_subtechnique: true
    output_path: dataset/minerva/scenario_to_technique.jsonl
    seed: 1337
  SCENARIO_TACTIC:
    output_path: dataset/minerva/scenario_to_tactics.jsonl
    seed: 1337
    max_items: 999999999
  SCENARIO_MITIGATION:
    output_path: dataset/minerva/scenario_to_mitigations.jsonl
    seed: 1337
    max_items: 999999999
  SCENARIO_DETECTION:
    output_path: dataset/minerva/scenario_to_detections.jsonl
    seed: 1337
    max_items: 999999999
  CVE_ATTACK_CHAIN:
    min_words: 15
    output_path: dataset/minerva/cve_to_attack_chain.jsonl
    seed: 1337
    max_items: 0
  CAPEC_EXAMPLE_CAPEC:
    output_path: dataset/minerva/capec_example_to_capec.jsonl
    seed: 1337
  CAPEC_EXAMPLE_CWE:
    output_path: dataset/minerva/capec_example_to_cwe.jsonl
    seed: 1337
  CAPEC_EXAMPLE_ATTACK:
    output_path: dataset/minerva/capec_example_to_attack.jsonl
    seed: 1337
  THREAT_ACTOR:
    output_path: dataset/minerva/threat_actor.jsonl
    seed: 1337
    alias_csv_path: rlvr/verl/utils/reward_score/aliases.csv
    binning:
      min_techniques: 3
      bin_count: 6
      target_questions_per_bin: 100
      questions_start: 3
      questions_step: 1
  CWE_CODE:
    output_path: dataset/minerva/cwe_code_to_cwe.jsonl
